feat: Add ProductCard and SwatchBar components
bloomreach/limitless-ui-react pull request #10
Opened 2024-09-23 05:02 UTC by anandgorantala

2024-09-23 23:11 UTC, joerideg submitted a review, later dismissed
Looks good to me. I do think the compound component pattern works great here. 

Could use some tests but lets say we will add those soon :)

2024-09-23 23:14 UTC, joerideg requested changes
Requesting that you remove the price formatting part.

2024-09-23 23:29 UTC, anandgorantala commented on src/utils/format-price.ts
> +export const formatPrice = (price: number, currency: string) => {
Good catch, I missed the locale  I had this function in every one of the code samples, so thought this, along with the component would be handy to have as part of the UI Kit.  wdyt about making the locale also an argument?

2024-09-24 16:45 UTC, joerideg commented on src/utils/format-price.ts
> +export const formatPrice = (price: number, currency: string) => {
"It's still optional to use, customers can choose to not import this if they have their own formatter"
Yes I think if its optional and configurable (maybe check if the format prop is passed?) it should be a good utility

2024-09-24 17:29 UTC, joerideg approved these changes

2024-09-24 18:25 UTC, merged